config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  resources :events, only: [:new, :show, :create, :edit, :update, :destroy]do
    member do
      get :liking_users
    end
  end

  resources :users, only: [:index, :show, :edit, :update]do
    member do
      get :like_events

    end
  end

  root 'home#top'
  get '/about' => 'home#about'

  post 'like/:event_id' => 'likes#like', as: 'like'
  delete 'unlike/:event_id' => 'likes#unlike', as: 'unlike'

  post 'friendship' => 'friendships#create'
  delete 'friendship' => 'friendships#destroy'
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true, length: {maximum: 400}
  validates :user_id, presence: true

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

  belongs_to :user
  belongs_to :friend, :class_name => "User"

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # K.K following functions are temporary deleted  :recoverable, :rememberable, :trackable,
  devise :database_authenticatable, :registerable,
         :validatable
  validates :name, presence: true
  validates :about, length:{maximum: 140}

  has_many :events
  has_many :likes
  has_many :like_events, through: :likes, source: :event

  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user
  
  def set_image(file)
    if !file.nil?
      file_name = file.original_filename
      File.open("public/user_images/#{file_name}", 'wb'){|f|f.write(file.read)}
      self.image = file_name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)<<:name
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy, :liking_users]
  before_action :correct_user, only: [:edit, :update]
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def liking_users
    @users = @event.liking_users
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :content)
    end

    def correct_user
      event = Event.find(params[:id])
      if !current_user?(event.user)
        redirect_to root_path
      end
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id])
  if @friendship.save
    flash[:notice] = "Added friend."
    redirect_to user_path(current_user.id)
  else
    flash[:error] = "Unable to add friend."
    redirect_to root_path
  end
  end

  def destroy
    @friendship = current_user.friendships.find_by(friend_id: params[:friend_id])
    @friendship.destroy
    flash[:notice] = "Removed friendship."
    redirect_to current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def top
      if user_signed_in?
        @event = Event.new
        @events = Event.all
      end
    end

    def about
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def like
    @event= Event.find(params[:event_id])
    like = current_user.likes.build(event_id: @event.id)
    like.save
  end

  def unlike
    @event = Event.find(params[:event_id])
    like = current_user.likes.find_by(event_id: @event.id)
    like.destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy, :like_notes]
  before_action :correct_user, only: [:edit, :update]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @events = Event.all.order(created_at: :desc)
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  # def create
  #  @user = User.new(user_params)
  #  file = params[:user][:image]
  #  @user.set_image(file)
#
#    respond_to do |format|
#      if @user.save
#        format.html { redirect_to @user, notice: 'User was successfully created.' }
#        format.json { render :show, status: :created, location: @user }
#      else
#        format.html { render :new }
#        format.json { render json: @user.errors, status: :unprocessable_entity }
#      end
#    end
#  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    file = params[:user][:image]
    @user.set_image(file)
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  # def destroy
  #  @user.destroy
  #  respond_to do |format|
  #    format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #    format.json { head :no_content }
  #  end
  #end
  def like_notes
    @notes = @user.like_notes
    @title = "List of Interested Events" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :nickname, :about, :image, :city, :interest)
    end

    def correct_user
      user = User.find(params[:id])
      if !current_user?(user)
        redirect_to root_path
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    current_user.id == user.id    
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def image_for(user)
     if user.image
      image_tag "/user_images/#{user.image}"
     else
      image_tag "default.png"
     end
  end
end

app/views/events/_event.html.erb
<li>
  <%= image_for(event.user) %>
  <span class="user-name">
    <%= event.user.name %>
  </span>
  <span class="content">
    <%= link_to event.title, event_path(event.id) %>
  </span>
  <span>
    <%= event.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  </span>
</li>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.content %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/liking_users.html.erb
<h2 class="heading">いいねしているユーザー一覧 </h2>
<ul class='user-list'>
  <%= render @users %>
</ul>

app/views/events/new.html.erb
<h1>Your New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @event.content %>
</p>

<div id="like-link">
<%= render 'likes/like_links', event: @event %>
</div>

<div>
  <small>
    <%= link_to @event.likes.count, liking_users_event_path(@event.id), id:"like-count", remote: true %>人がいいね！といっています
  </small>
</div>

<% if current_user?(@event.user) %>
  <%= link_to 'Edit', edit_event_path(@event.id) %> |
<% end %>
<%= link_to 'Back', :back %>

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/home/about.html.erb
This page gonna explain what is this service for

app/views/home/top.html.erb
<h1>This is top page</h1>

<% if user_signed_in? %>
  <p> U R Logged in </p>
<% else %>
  <p> U need to Log in or register </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Optime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar">
    <div class="container">
      <div id="logo"><li><%= link_to "OpTime", root_path %></li></div>
      <% if !user_signed_in? %>
        <ul class="header-right">
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
          <li><%= link_to "このサイトについて", about_path %></li>
        </ul>
      <% else %>
        <ul class="header-right">
          <li><%= link_to "Event", new_event_path %></li>
          <li><%= link_to "Recommendation", "#" %></li>
          <li><%= link_to "About User", user_path(current_user.id) %></li>
          <li><%= link_to "=>Professional", "#" %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        </ul>
      <% end %>
    </div>
  </header>

  <div class="container">
    <%= yield %>
  </div>

  <div class="container">
    <footer class="footer">
      <div class="small">
        &copy; 2016 OpTime, Inc. -Keisuke Kawahara-
      </div>
    </footer>
  </div>
</body>
</html>

app/views/likes/_like_links.html.erb
<% if current_user.likes.find_by(event_id: event.id) %>
  <%= link_to 'いいね！を取り消す', unlike_path(event.id), method: :delete, remote: true %>
<% else %>
  <%= link_to 'いいね！', like_path(event.id), method: :post, remote: true %>
<% end %>

app/views/likes/like.js.erb
$('#like-link').html('<%= escape_javascript(render("likes/like_links", event: @event)) %>');

$('#like-count').html('<%= @event.likes.count %>');

app/views/likes/unlike.js.erb
$('#like-link').html('<%= escape_javascript(render("likes/like_links", event: @event  )) %>');

$('#like-count').html('<%= @event.likes.count %>');

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :interest %><br>
    <%= f.text_field :interest %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image  %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/_user.html.erb
<li>
  <%= image_for(user) %>
  <%= link_to user.name, user %> 
</li>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to "Personal_Setting", edit_user_registration_path %>|
<%= link_to 'Show', @user %> |
<%= link_to 'Back', :back %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Nickname</th>
      <th>About</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <% unless current_user.id == user.id %>
      <tr>
        <%= image_for(user) %>
        <td><%= user.name %></td>
        <td><%= user.nickname %></td>
        <td><%= user.about %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if !current_user.friendships.find_by(friend_id: user.id) %>
        <td><%= link_to "Add Friend", friendship_path(friend_id: user), method: :post %></td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>ユーザー新規登録</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<aside class="sidebar">
  <div class="user-info">
    <h3>
      <%= image_for(@user) %>
    </h3>
    <span class="label">Name</span>
    <h3><%= @user.name %></h3>
    <span class="label">City</span>
    <h3><%= @user.city %></h3>
    <span class="label">Interest</span>
    <h3><%= @user.city %></h3>
    <span class="label">About</span>
    <h3><%= @user.about %></h3>
    <h2>Friends</h2>
    <ul>
      <% @user.friends.each do |friend| %>
        <li>
          <%= friend.name %>
          <%= link_to "remove", friendship_path(friend_id: friend), method: :delete %>
        </li>
      <% end %>
    </ul>

    <p><%= link_to "Find Friends", users_path %></p>

    <h2>Friended by Users</h2>
    <ul>
      <% @user.inverse_friends.each do |user| %>
        <li><%= user.name %></li>
      <% end %>
    </ul>
  </div>

  <% if current_user?(@user) %>
    <%= link_to 'Edit', edit_user_path(@user), {class: "btn edit-btn"} %>
  <% end %>
</aside>

<ul class="notes">
  <h2>Feed Line</h2>
  <%= render @events %>
</ul>